### PR TITLE
Support MC 1.20.2 for Fabric

### PR DESCRIPTION
**Pull request by BluSpring**

### CODE REVIEW

**Review by WiIIiam278 — APPROVED** [review]
Sure, thanks. Saves me the job. Looks good.

**Comment by BluSpring** [comment]
hold on, don't merge yet, need to fix some things

**Comment by WiIIiam278** [comment]
All good, I was planning on testing first anyway.

**Comment by BluSpring** [comment]
Okay, so I'm currently running into a problem here where the client seems to run into an EOFException when it receives the packet, and I just cannot figure out *why* that is the case.

**Comment by WiIIiam278** [comment]
Don't you have to read the identifier bytes first? I had to make a change like this for HH

**Comment by BluSpring** [comment]
With this one, I don't think so? That would have to be done if I did `packet.write` instead of `packet.payload().write`, so that shouldn't have to be the case.

**Comment by WiIIiam278** [comment]
Oh interesting. Sounds like I over complicated my HH code

**Comment by WiIIiam278** [comment]
Superseeded by #95 - we ended up removing the mixin and registering a packet handler.

**Pull request closed without merging**
